Attempt nvdrain only when the driver is loaded, this will avoid nvdrain on node reboot
Signed-off-by: Shiva Krishna, Merla <smerla@nvidia.com>

diff --git a/driver-manager b/driver-manager
--- a/driver-manager
+++ b/driver-manager
@@ -545,29 +545,29 @@ uninstall_driver() {
     # always evict all gpu-operator components across a driver restart
     _evict_all_gpu_operator_components || _exit_failed
 
-    # delete any GPU pods running on the node
-    if _is_gpu_pod_eviction_enabled; then
-        _cordon_k8s_node
-        _nvdrain_k8s_node
-        if [ "$?" != "0" ]; then
-            # nvdrain will only return non-zero code when GPU pods
-            # are running on the node and cannot be deleted. Attempt
-            # to drain the node in this case.
-            echo "Failed to drain node of GPU pods"
-            if ! _is_auto_drain_enabled; then
-                echo "Cannot proceed until all GPU pods are drained from the node. Exiting."
-                _exit_failed
-            fi
-            echo "Attempting node drain"
-            trap '_exit_failed' ERR
-            _drain_k8s_node
-            _cleanup_driver
-        fi
-    fi
-
-
     # check if driver is already loaded
     if _driver_loaded; then
+        # Always evict GPU pods when pod eviction is enabled.
+        # This is because, there can be idle GPU pods which will allow
+        # driver to be unloaded but fail later on due to stale references. More details in the issue
+        # https://github.com/NVIDIA/gpu-operator/issues/416
+        if _is_gpu_pod_eviction_enabled; then
+            _cordon_k8s_node
+            _nvdrain_k8s_node
+            if [ "$?" != "0" ]; then
+                # nvdrain will only return non-zero code when GPU pods
+                # are running on the node and cannot be deleted. Attempt
+                # to drain the node in this case.
+                echo "Failed to drain node of GPU pods"
+                if ! _is_auto_drain_enabled; then
+                    echo "Cannot proceed until all GPU pods are drained from the node. Exiting."
+                    _exit_failed
+                fi
+                echo "Attempting node drain"
+                trap '_exit_failed' ERR
+                _drain_k8s_node
+            fi
+        fi
         _cleanup_driver
         if [ "$?" != "0" ]; then
             if _is_auto_drain_enabled; then
