Evict NVSM pod during driver upgrades

diff --git a/driver-manager b/driver-manager
--- a/driver-manager
+++ b/driver-manager
@@ -26,6 +26,7 @@ PLUGIN_DEPLOYED=""
 GFD_DEPLOYED=""
 DCGM_DEPLOYED=""
 DCGM_EXPORTER_DEPLOYED=""
+NVSM_DEPLOYED=""
 TOOLKIT_DEPLOYED=""
 VALIDATOR_DEPLOYED=""
 MIG_MANAGER_DEPLOYED=""
@@ -144,6 +145,13 @@ _fetch_current_labels() {
     fi
     echo "Current value of 'nvidia.com/gpu.deploy.mig-manager=${MIG_MANAGER_DEPLOYED}'"
 
+    echo "Getting current value of the 'nvidia.com/gpu.deploy.nvsm' node label"
+    NVSM_DEPLOYED=$(kubectl get nodes ${NODE_NAME} -o=jsonpath='{$.metadata.labels.nvidia\.com/gpu\.deploy\.nvsm}')
+    if [ "${?}" != "0" ]; then
+        echo "Unable to get the value of the 'nvidia.com/gpu.deploy.nvsm' label"
+        exit 1
+    fi
+    echo "Current value of 'nvidia.com/gpu.deploy.nvsm=${NVSM_DEPLOYED}'"
 }
 
 _evict_gpu_operator_components() {
@@ -155,7 +163,8 @@ _evict_gpu_operator_components() {
         nvidia.com/gpu.deploy.device-plugin=$(_maybe_set_paused ${PLUGIN_DEPLOYED}) \
         nvidia.com/gpu.deploy.gpu-feature-discovery=$(_maybe_set_paused ${GFD_DEPLOYED}) \
         nvidia.com/gpu.deploy.dcgm-exporter=$(_maybe_set_paused ${DCGM_EXPORTER_DEPLOYED}) \
-        nvidia.com/gpu.deploy.dcgm=$(_maybe_set_paused ${DCGM_DEPLOYED})
+        nvidia.com/gpu.deploy.dcgm=$(_maybe_set_paused ${DCGM_DEPLOYED}) \
+        nvidia.com/gpu.deploy.nvsm=$(_maybe_set_paused ${NVSM_DEPLOYED})
 
     if [ "$?" != "0" ]; then
         return 1
@@ -242,7 +251,8 @@ _reschedule_gpu_operator_components() {
         nvidia.com/gpu.deploy.device-plugin=$(_maybe_set_true ${PLUGIN_DEPLOYED}) \
         nvidia.com/gpu.deploy.gpu-feature-discovery=$(_maybe_set_true ${GFD_DEPLOYED}) \
         nvidia.com/gpu.deploy.dcgm-exporter=$(_maybe_set_true ${DCGM_EXPORTER_DEPLOYED}) \
-        nvidia.com/gpu.deploy.dcgm=$(_maybe_set_true ${DCGM_DEPLOYED})
+        nvidia.com/gpu.deploy.dcgm=$(_maybe_set_true ${DCGM_DEPLOYED}) \
+        nvidia.com/gpu.deploy.nvsm=$(_maybe_set_true ${NVSM_DEPLOYED})
 
     if [ "$?" != "0" ]; then
         return 1
